global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "customer-service"
    static_configs:
      - targets: ["customer-service:8000"]

  - job_name: "restaurant-service"
    static_configs:
      - targets: ["restaurant-service:8001"]

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:8002"]

  - job_name: "delivery-service"
    static_configs:
      - targets: ["delivery-service:8003"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8004"]

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:8005"]
